# Generated by Django 3.0.7 on 2024-11-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_stock_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
