# Generated by Django 3.0.7 on 2024-11-12 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20241112_1004'),
    ]

    operations = [
    ]
