# Generated by Django 3.0.7 on 2024-11-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_stockhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='product_name',
            new_name='brand_name',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='date_last_updated',
            new_name='last_updated',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='category',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='code',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='id',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='medicine_type',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='threshold',
        ),
        migrations.AddField(
            model_name='stock',
            name='dosage_strength',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='form',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='generic_name',
            field=models.CharField(default=23, max_length=100),
            preserve_default=False,
        ),
       migrations.AddField(
    model_name='stock',
    name='item_no',
    field=models.AutoField(primary_key=True),
),

        migrations.AddField(
            model_name='stockhistory',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='quantity_added',
            field=models.IntegerField(),
        ),
    ]
